export const stakerAbi = [
  {
    inputs: [
      {
        internalType: "contract Storage",
        name: "storageAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "CannotWithdrawUnder150CollateralizationRatio",
    type: "error",
  },
  { inputs: [], name: "ContractNotFound", type: "error" },
  { inputs: [], name: "ContractPaused", type: "error" },
  { inputs: [], name: "PPYLocked", type: "error" },
  { inputs: [], name: "InsufficientBalance", type: "error" },
  { inputs: [], name: "InvalidOrOutdatedContract", type: "error" },
  { inputs: [], name: "InvalidRewardsStartTime", type: "error" },
  { inputs: [], name: "MustBeGuardian", type: "error" },
  { inputs: [], name: "MustBeGuardianOrValidContract", type: "error" },
  { inputs: [], name: "MustBeMultisig", type: "error" },
  { inputs: [], name: "NotAuthorized", type: "error" },
  { inputs: [], name: "StakerNotFound", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PPYStaked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PPYWithdrawn",
    type: "event",
  },
  {
    inputs: [],
    name: "authorizedStaker",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "decreasePLSAssigned",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "decreasePLSStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "decreasePLSValidating",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "decreasePPYRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getPLSAssigned",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getPLSStake",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getPLSValidating",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getPLSValidatingHighWater",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getCollateralizationRatio",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getEffectivePPYStaked",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getEffectiveRewardsRatio",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getPPYRewards",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getPPYStake",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getIndexOf",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getLastRewardsCycleCompleted",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getMinimumPPYStake",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "getRewardsStartTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "int256", name: "stakerIndex", type: "int256" }],
    name: "getStaker",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "stakerAddr",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "PLSAssigned",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PLSStaked",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PLSValidating",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PLSValidatingHighWater",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PPYRewards",
            type: "uint256",
          },
          { internalType: "uint256", name: "PPYStaked", type: "uint256" },
          {
            internalType: "uint256",
            name: "lastRewardsCycleCompleted",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "rewardsStartTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PPYLockedUntil",
            type: "uint256",
          },
        ],
        internalType: "struct Staking.Staker",
        name: "staker",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getStakerCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "offset", type: "uint256" },
      { internalType: "uint256", name: "limit", type: "uint256" },
    ],
    name: "getStakers",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "stakerAddr",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "PLSAssigned",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PLSStaked",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PLSValidating",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PLSValidatingHighWater",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PPYRewards",
            type: "uint256",
          },
          { internalType: "uint256", name: "PPYStaked", type: "uint256" },
          {
            internalType: "uint256",
            name: "lastRewardsCycleCompleted",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "rewardsStartTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "PPYLockedUntil",
            type: "uint256",
          },
        ],
        internalType: "struct Staking.Staker[]",
        name: "stakers",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalPPYStake",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "increasePLSAssigned",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "increasePLSStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "increasePLSValidating",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "increasePPYRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "stakerAddr", type: "address" }],
    name: "requireValidStaker",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "restakePPY",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "setPLSValidatingHighWater",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "cycleNumber", type: "uint256" },
    ],
    name: "setLastRewardsCycleCompleted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "time", type: "uint256" },
    ],
    name: "setRewardsStartTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "PPYAmt", type: "uint256" },
    ],
    name: "slashPPY",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "stakePPY",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "stakerAddr", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "PPYLockedUntil", type: "uint256" },
    ],
    name: "stakePPYOnBehalfOf",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "withdrawPPY",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
